#spring:
#  profiles:
#    active: @activatedProperties@
#Server config
server:
  #port: ${PORT:8082}
  address: ${SERVER_ADDRESS}
  #ssl:
  #  enabled: true
  #  protocol: TLS
  #  key-store-type: PKCS12
  #  key-store: classpath:keystore/precionline-api-cert.p12
  #  key-store-password: L9VrMWxwhVrDv4LxtFj2
  servlet:
    context-path: /precionline/api/v1

#MySql configuration
spring:
  application:
    name: apirest
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:40878/railway
    username: root
    password: sEVRqTvDqxblVFQrkBksYplzhSfylrUB
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: precionline
      password: pruebas1234!