#Server config
server:
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /precionline/api/v1

#MySql configuration
spring:
  application:
    name: apirest
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:40878/railway
    username: root
    password: sEVRqTvDqxblVFQrkBksYplzhSfylrUB
  jpa:
    hibernate:
      ddl-auto: update

