#Server config
server:
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /precionline/api/v1

#MySql configuration
spring:
  application:
    name: apirest
  datasource:
    #url: jdbc:mysql://roundhouse.proxy.rlwy.net:40878/railway
    url: jdbc:mysql://mysql.railway.internal/railway
    username: root
    password: sEVRqTvDqxblVFQrkBksYplzhSfylrUB
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      table-prefix=spring_batch: BATCH_

#Application Config
#TODO Sacar Token a variable de entorno
precionline:
  server:
    ip: 100.64.0.2 #Deprecated Issue#13
  origins: \*
  cron: 0 30 18 * * *
  ree:
    token: 608773a53bb93c375e5e5a1ea658f684df8b6777cec2c2d2c8e2602fbbabf4a0
    indicator:
      1001: https://api.esios.ree.es/indicators/1001

